### PR TITLE
Fix of build without DRM or WAYLAND

### PR DESCRIPTION
**Pull request by santucco**
Fix of a build when WITH_DRM=OFF or WITH_WAYLAND=OFF specified

### CODE REVIEW

**Comment by andr2000** [comment]
If I try
`cmake ../ -DWITH_DRM=OFF -DWITH_WAYLAND=OFF -DWITH_IVI_EXTENSION=ON -DWITH_INPUT=ON`
then I get
```
CMake Error at CMakeLists.txt:55 (message):
  Can't enable zero copy without DRM.

```
If this is the issue you are facing then proper fix might be forcing `-DWITH_ZCOPY=OFF`

**Comment by santucco** [comment]
Problem is Exception is not a member of DisplayItf.

I am trying to make a build without Wayland:
$ cmake  -DWITH_DRM=ON -DWITH_WAYLAND=OFF -DWITH_IVI_EXTENSION=ON -DWITH_INPUT=ON . 
That is ok.
$ make
/home/santucco/tmp/xen-troops/displ_be/src/main.cpp: In function ‘DisplayItf::DisplayPtr getDisplay(DisplayMode)’:
/home/santucco/tmp/xen-troops/displ_be/src/main.cpp:211:21: error: ‘Exception’ is not a member of ‘DisplayItf’
  211 |   throw DisplayItf::Exception("WAYLAND mode is not supported", EINVAL);

If I do that without DRM, I believe it will be almost the same error, but I do not have wayland's stuff and can't check.

**Comment by andr2000** [comment]
```
cmake .. -DWITH_DRM=OFF -DWITH_ZCOPY=OFF -DWITH_WAYLAND=ON -DWITH_IVI_EXTENSION=ON -DWITH_INPUT=ON

displ_be/src/main.cpp:216:21: error: 'Exception' is not a member of 'DisplayItf'
   throw DisplayItf::Exception("DRM mode is not supported", EINVAL);
                     ^~~~~~~~~

```
This also fails

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Comment by andr2000** [comment]
@al1img please take a look

**Comment by al1img** [comment]
`Reviewed-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>`

**Comment by andr2000** [comment]
Please update the commit with "Reviewed-by" appended.

**Pull request merged**
